### PR TITLE
RDKBACCL-274 :  Adding meta layers

### PR DESCRIPTION
**Pull request by anatar818**
RDKBACCL-274 :  Adding meta layers and removing Turris flag

Reason for change : Integration of ccsp components after removing Turris flag
Test Procedure: Build and flash the image.erouter0 should get ip
Risks: None

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Anatar: Please add the standard licensing files at top level:
LICENSE: As https://github.com/rdkcentral/meta-rdk-wan/blob/main/LICENSE
COPYING: Soft link to LICENSE
CONTRIBUTING.md: https://github.com/rdkcentral/meta-rdk-wan/blob/main/CONTRIBUTING.md
NOTICE: https://github.com/rdkcentral/meta-rdk-wan/blob/main/NOTICE

Then please append a credit to Cisco to NOTICE:
```
Copyright [2014] [Cisco Systems, Inc.]
Licensed under the Apache License, Version 2.0
```

and I will clear off the check.

**Comment by anatar818** [comment]
> Hi Anatar: Please add the standard licensing files at top level: LICENSE: As https://github.com/rdkcentral/meta-rdk-wan/blob/main/LICENSE COPYING: Soft link to LICENSE CONTRIBUTING.md: https://github.com/rdkcentral/meta-rdk-wan/blob/main/CONTRIBUTING.md NOTICE: https://github.com/rdkcentral/meta-rdk-wan/blob/main/NOTICE
> 
> Then please append a credit to Cisco to NOTICE:
> 
> ```
> Copyright [2014] [Cisco Systems, Inc.]
> Licensed under the Apache License, Version 2.0
> ```
> 
> and I will clear off the check.


But why Cisco I dont get the point.

**Comment by mhughesacn** [comment]
Hi Anatar: The file bbhm_def_cfg_banana.xml has a Cisco copyright in the header meaning that there is Cisco content there, hence the need for a credit.

**Comment by anatar818** [comment]
> Copyright [2014] [Cisco Systems, Inc.]
> Licensed under the Apache License, Version 2.0

Hi
the license is very huge , should be add the entire license or link to that is enough
LICENSE: As https://github.com/rdkcentral/meta-rdk-wan/blob/main/LICENSE

**Comment by mhughesacn** [comment]
Hi Anatar: LICENSE should contain the entire license text please, not a link.  Sorry if that wasn't clear.

**Comment by anatar818** [comment]
[NOTICE.txt](https://github.com/user-attachments/files/16635904/NOTICE.txt)
[LICENSE.txt](https://github.com/user-attachments/files/16635906/LICENSE.txt)
[CONTRIBUTING.md](https://github.com/user-attachments/files/16635908/CONTRIBUTING.md)
[COPYING](https://github.com/rdkcentral/meta-rdk-wan/blob/main/LICENSE)

**Comment by anatar818** [comment]
Will create a new request

**Pull request closed without merging**
